import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const sizeMap = {
    "8x2": { w: 520, h: 120 },
    "6x2": { w: 420, h: 120 },
    "4x2": { w: 320, h: 120 },
};
function CardTitle({ title }) {
    return (_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[16px] sm:text-[18px] font-bold text-[#111827]", children: title }), _jsx("div", { className: "text-[11px] text-[#6b7280] mt-1", children: "Preview how the Screen will look" })] }));
}
function LiveScreenPreviewFinal({ draft, onOpenGuestList, onOpenWalkingGuest, }) {
    const headerBg = "/bg-images/previewheaderbg.png";
    const hasLogo = !!draft.screenLogoUrl;
    return (_jsxs("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-6 min-h-[430px] flex flex-col items-center justify-center", children: [_jsx(CardTitle, { title: "Live Screen Preview" }), _jsx("div", { className: "mt-10 w-full flex justify-center", children: _jsx("div", { className: "w-full max-w-[520px]", children: _jsxs("div", { className: "rounded-2xl overflow-hidden border border-[#ececec] shadow-[0_18px_55px_rgba(0,0,0,0.18)] bg-white", children: [_jsx("div", { className: "relative bg-cover bg-center bg-no-repeat px-5 py-6 text-white", style: { backgroundImage: `url('${headerBg}')` }, children: _jsxs("div", { className: "grid grid-cols-[70px_1fr_70px] items-center", children: [_jsx("div", { className: "flex items-center justify-start", children: hasLogo ? (_jsx("img", { src: draft.screenLogoUrl, alt: "Logo", className: "h-16 w-auto object-contain" })) : null }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[9px] tracking-[0.25em] font-semibold opacity-95", children: "WELCOME TO" }), _jsx("div", { className: "mt-1 text-[16px] font-extrabold leading-tight text-[#111827]", children: draft.templateName || "EVENT NAME" })] }), _jsx("div", {})] }) }), _jsxs("div", { className: "p-5 bg-white", children: [_jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3", children: [_jsx("button", { type: "button", className: "cursor-pointer w-full h-10 rounded-lg text-white text-[12px] font-semibold bg-gradient-to-b from-[#008236] to-[#00A63E]", children: "Check In" }), draft.enableCheckoutTag ? (_jsx("button", { type: "button", className: "cursor-pointer w-full h-10 rounded-lg text-white text-[12px] font-semibold bg-gradient-to-b from-[#E0656A] to-[#9B353A]", children: "Check Out" })) : null, _jsx("button", { type: "button", onClick: onOpenGuestList, className: "cursor-pointer w-full h-10 rounded-lg text-white text-[12px] font-semibold bg-[linear-gradient(90deg,#ffc145_0%,#dba61f_100%)]", children: "Guest List" }), _jsx("button", { type: "button", onClick: onOpenWalkingGuest, className: "cursor-pointer w-full h-10 rounded-lg text-white text-[12px] font-semibold bg-[linear-gradient(90deg,#ffc145_0%,#dba61f_100%)]", children: "Add Walking Guest" })] }), _jsx("div", { className: "mt-3 text-center text-[11px] text-[#6b7280]", children: "Preview how the Screen will look" })] })] }) }) })] }));
}
function CheckInTagPreviewFinal({ draft, tagSize, }) {
    const size = sizeMap[tagSize];
    const bg = draft.checkInBgUrl || "/bg-images/previewheaderbg.png";
    const logo = draft.checkInLogoUrl || draft.screenLogoUrl;
    return (_jsxs("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-6 min-h-[205px] flex flex-col items-center justify-center", children: [_jsx(CardTitle, { title: "Check In Tag Preview" }), _jsx("div", { className: "mt-8 w-full flex justify-center", children: _jsx("div", { className: "rounded-xl overflow-hidden border border-[#ececec] shadow-[0_18px_55px_rgba(0,0,0,0.18)]", style: { width: size.w, height: size.h, maxWidth: "100%" }, children: _jsx("div", { className: "w-full h-full bg-cover bg-center bg-no-repeat px-6 flex items-center", style: { backgroundImage: `url('${bg}')` }, children: _jsxs("div", { className: "w-full grid grid-cols-[70px_1fr_70px] items-center", children: [_jsx("div", { className: "flex items-center justify-start", children: logo ? (_jsx("img", { src: logo, alt: "Logo", className: "h-16 w-auto object-contain" })) : null }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[11px] font-extrabold tracking-wide text-[#111827] uppercase", children: draft.templateName || "Event Name" }), _jsx("div", { className: "mt-2 text-[18px] sm:text-[20px] font-extrabold text-[#111827] leading-tight", children: "John Smith" }), _jsx("div", { className: "text-[12px] font-medium text-[#374151] opacity-80 leading-tight", children: "Groom's Uncle" })] }), _jsx("div", {})] }) }) }) })] }));
}
function CheckOutTagPreviewFinal({ draft, tagSize, text, }) {
    const size = sizeMap[tagSize];
    const message = text?.trim().length ? text : "Thank You For Coming";
    const bg = draft.checkOutBgUrl || "/bg-images/checkoutbg.png";
    const logo = draft.checkOutLogoUrl || draft.screenLogoUrl;
    return (_jsxs("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-6 min-h-[205px] flex flex-col items-center justify-center", children: [_jsx(CardTitle, { title: "Check Out Tag Preview" }), _jsx("div", { className: "mt-8 w-full flex justify-center", children: _jsx("div", { className: "rounded-xl overflow-hidden border border-[#ececec] shadow-[0_18px_55px_rgba(0,0,0,0.18)]", style: { width: size.w, height: size.h, maxWidth: "100%" }, children: _jsx("div", { className: "w-full h-full bg-cover bg-center bg-no-repeat px-6 flex items-center", style: { backgroundImage: `url('${bg}')` }, children: _jsxs("div", { className: "w-full grid grid-cols-[70px_1fr_70px] items-center", children: [_jsx("div", { className: "flex items-center justify-start", children: logo ? (_jsx("img", { src: logo, alt: "Logo", className: "h-16 w-auto object-contain" })) : null }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[11px] font-extrabold tracking-wide text-[#111827] uppercase", children: draft.templateName || "Event Name" }), _jsx("div", { className: "mt-2 text-[16px] sm:text-[18px] font-extrabold text-[#111827] leading-tight", children: message })] }), _jsx("div", {})] }) }) }) })] }));
}
export default function Step4Finalizing({ draft, onOpenGuestList, onOpenWalkingGuest, }) {
    return (_jsxs("div", { className: "mt-6 grid grid-cols-1 lg:grid-cols-2 gap-5", children: [_jsx(LiveScreenPreviewFinal, { draft: draft, onOpenGuestList: onOpenGuestList, onOpenWalkingGuest: onOpenWalkingGuest }), _jsxs("div", { className: "space-y-5", children: [_jsx(CheckInTagPreviewFinal, { draft: draft, tagSize: draft.checkInTagSize }), draft.enableCheckoutTag && (_jsx(CheckOutTagPreviewFinal, { draft: draft, tagSize: draft.checkOutTagSize, text: draft.checkOutTagText }))] })] }));
}
