import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function Step3CheckOutTag({ draft, variant, tagSize, onTagSizeChange, text, onTextChange, onAddBackground, onAddLogo, uploading, }) {
    const selectClass = "w-full h-10 rounded-lg border border-[#e5e7eb] bg-white px-4 text-[13px] text-black outline-none focus:border-[#FCC125] shadow-[0_10px_25px_rgba(0,0,0,0.08)]";
    const inputClass = "w-full h-10 rounded-lg border border-[#e5e7eb] bg-white px-4 text-[13px] text-black outline-none focus:border-[#FCC125] shadow-[0_10px_25px_rgba(0,0,0,0.08)]";
    const sizeMap = {
        "8x2": { w: 520, h: 120 },
        "6x2": { w: 420, h: 120 },
        "4x2": { w: 320, h: 120 },
    };
    if (variant === "details") {
        return (_jsxs("div", { className: "space-y-5", children: [_jsxs("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-5", children: [_jsx("div", { className: "text-[14px] font-bold text-[#111827]", children: "Check Out Tag Template Details" }), _jsx("div", { className: "text-[11px] text-[#6b7280] mt-1", children: "Configure your badge template settings" }), _jsxs("div", { className: "mt-4 space-y-4", children: [_jsxs("div", { children: [_jsx("div", { className: "text-[12px] font-semibold text-[#111827] mb-2", children: "Select Tag Size" }), _jsxs("div", { className: "relative", children: [_jsxs("select", { value: tagSize, onChange: (e) => onTagSizeChange?.(e.target.value), className: `${selectClass} pr-10 appearance-none`, children: [_jsx("option", { value: "8x2", children: "8x2" }), _jsx("option", { value: "6x2", children: "6x2" }), _jsx("option", { value: "4x2", children: "4x2" })] }), _jsx("span", { className: "pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#6b7280]", children: _jsx("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", "aria-hidden": "true", children: _jsx("path", { d: "M6 9l6 6 6-6", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }) }) })] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[12px] font-semibold text-[#111827] mb-2", children: "Write text" }), _jsx("input", { value: text, onChange: (e) => onTextChange?.(e.target.value), placeholder: "Write text", className: inputClass })] })] })] }), _jsx("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-5 min-h-fit", children: _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx("button", { type: "button", disabled: !!uploading, className: "cursor-pointer h-14 rounded-xl bg-[#2f2f2f] text-white text-[12px] font-semibold disabled:opacity-60", onClick: () => onAddBackground?.(), children: "Add Background" }), _jsx("button", { type: "button", disabled: !!uploading, className: "cursor-pointer h-14 rounded-xl bg-[#2f2f2f] text-white text-[12px] font-semibold disabled:opacity-60", onClick: () => onAddLogo?.(), children: "Add Logo" })] }) })] }));
    }
    const size = sizeMap[tagSize];
    const message = text?.trim().length ? text : "Thank You For Coming";
    const bg = draft.checkOutBgUrl || "/bg-images/checkoutbg.png";
    const logo = draft.checkOutLogoUrl || draft.screenLogoUrl;
    return (_jsxs("div", { className: "bg-white border border-[#ececec] rounded-2xl shadow-sm p-4 sm:p-5 min-h-fit flex flex-col items-center justify-center", children: [_jsx("div", { className: "text-center text-[16px] sm:text-[18px] font-bold text-[#111827]", children: "Check Out Tag Preview" }), _jsx("div", { className: "mt-8 w-full flex justify-center", children: _jsx("div", { className: "rounded-xl overflow-hidden border border-[#ececec] shadow-[0_18px_55px_rgba(0,0,0,0.18)]", style: { width: size.w, height: size.h, maxWidth: "100%" }, children: _jsx("div", { className: "w-full h-full bg-cover bg-center bg-no-repeat px-6 flex items-center", style: { backgroundImage: `url('${bg}')` }, children: _jsxs("div", { className: "w-full grid grid-cols-[70px_1fr_70px] items-center", children: [_jsx("div", { className: "flex items-center justify-start", children: logo ? (_jsx("img", { src: logo, alt: "Logo", className: "h-16 w-auto object-contain" })) : null }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[11px] font-extrabold tracking-wide text-[#111827] uppercase", children: draft.templateName || "Event Name" }), _jsx("div", { className: "mt-2 text-[16px] sm:text-[18px] font-extrabold text-[#111827]", children: message })] }), _jsx("div", {})] }) }) }) })] }));
}
