import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from "react-router-dom";
const base = "group w-full flex items-center gap-3 px-4 py-3 rounded-lg text-[14px] font-medium transition";
const inactive = "text-[#374151] hover:bg-[#E5E5E5] hover:text-[#374151]";
const active = "bg-[#ff2aa1] text-white shadow-[0_10px_30px_rgba(255,42,161,0.25)]";
const iconBase = "w-[18px] h-[18px] object-contain transition";
function SidebarNav() {
    return (_jsxs("nav", { className: "space-y-2", children: [_jsx(NavLink, { to: "/app/adminDashboard", className: ({ isActive }) => `${base} ${isActive ? active : inactive}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx("span", { className: "w-5 h-5 grid place-items-center", children: _jsx("img", { src: "/images/livedashboard.svg", alt: "Live Dashboard", className: `${iconBase} ${isActive ? "brightness-0 invert" : ""}` }) }), "Live Dashboard"] })) }), _jsx(NavLink, { to: "/app/templatesDashboard", className: ({ isActive }) => `${base} ${isActive ? active : inactive}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx("span", { className: "w-5 h-5 grid place-items-center", children: _jsx("img", { src: "/images/templates.svg", alt: "Templates", className: `${iconBase} ${isActive ? "brightness-0 invert" : ""}` }) }), "Templates"] })) }), _jsx(NavLink, { to: "/app/EventsDashboard", className: ({ isActive }) => `${base} ${isActive ? active : inactive}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx("span", { className: "w-5 h-5 grid place-items-center", children: _jsx("img", { src: "/images/events.svg", alt: "Events", className: `${iconBase} ${isActive ? "brightness-0 invert" : ""}` }) }), "Events"] })) }), _jsx(NavLink, { to: "/app/ReportsDashboard", className: ({ isActive }) => `${base} ${isActive ? active : inactive}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx("span", { className: "w-5 h-5 grid place-items-center", children: _jsx("img", { src: "/images/reports.svg", alt: "Reports", className: `${iconBase} ${isActive ? "brightness-0 invert" : ""}` }) }), "Reports"] })) })] }));
}
export default function AppSidebar({ isOpen, onClose }) {
    return (_jsxs(_Fragment, { children: [_jsx("aside", { className: "w-[240px] shrink-0 hidden lg:block", children: _jsx("div", { className: "bg-white border-r-1 border-[#ececec] p-4 h-full", children: _jsx(SidebarNav, {}) }) }), _jsxs("div", { className: `lg:hidden fixed inset-0 z-40 transition ${isOpen ? "pointer-events-auto" : "pointer-events-none"}`, children: [_jsx("button", { type: "button", onClick: onClose, "aria-label": "Close menu overlay", className: `absolute inset-0 bg-black/35 transition-opacity duration-300 ${isOpen ? "opacity-100" : "opacity-0"}` }), _jsxs("div", { className: `absolute left-0 top-0 h-full w-full bg-white border-r border-[#ececec] p-4
          shadow-[0_30px_80px_rgba(0,0,0,0.25)]
          transition-transform duration-300 ease-out
          ${isOpen ? "translate-x-0" : "-translate-x-full"}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("img", { src: "/images/ace-logo.png", alt: "Ace E Star", className: "h-9 w-auto object-contain" }), _jsx("button", { type: "button", onClick: onClose, className: "w-10 h-10 grid place-items-center rounded-lg hover:bg-[#f3f4f6]", "aria-label": "Close menu", children: _jsxs("svg", { width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M6 6l12 12", stroke: "#111827", strokeWidth: "2", strokeLinecap: "round" }), _jsx("path", { d: "M18 6L6 18", stroke: "#111827", strokeWidth: "2", strokeLinecap: "round" })] }) })] }), _jsx("div", { onClick: onClose, children: _jsx(SidebarNav, {}) })] })] })] }));
}
