import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function templateDot(template) {
    if (template === "Wedding")
        return "bg-[#DCFCE7] text-[#16a34a]";
    if (template === "Birthday")
        return "bg-[#DBEAFE] text-[#2563eb]";
    return "bg-[#F3E8FF] text-[#7c3aed]";
}
export default function EventRow({ item, onEndEvent, onShareDetails, onViewReport, }) {
    const ongoing = item.status === "On Going";
    return (_jsxs("tr", { className: "border-b border-[#f0f0f0] last:border-b-0 whitespace-nowrap", children: [_jsx("td", { className: "py-3 sm:py-4", children: _jsxs("div", { className: "flex items-center gap-2 sm:gap-3 min-w-0", children: [_jsx("div", { className: `w-8 h-8 sm:w-9 sm:h-9 rounded-full grid place-items-center shrink-0 ${templateDot(item.template)} overflow-hidden`, children: item.logoUrl ? (_jsx("img", { src: item.logoUrl, alt: "Event Logo", className: "w-full h-full object-cover", onError: (e) => {
                                    e.currentTarget.style.display = "none";
                                } })) : (_jsxs("svg", { width: "18", height: "18", viewBox: "0 0 24 24", fill: "none", "aria-hidden": "true", children: [_jsx("path", { d: "M12 12a4 4 0 1 0-4-4 4 4 0 0 0 4 4Z", stroke: "currentColor", strokeWidth: "2" }), _jsx("path", { d: "M4 21a8 8 0 0 1 16 0", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" })] })) }), _jsx("div", { className: "font-semibold min-w-0 max-w-[240px] sm:max-w-[340px] md:max-w-none truncate text-[#2E3646] text-[12px] sm:text-[13px]", children: item.name })] }) }), _jsx("td", { className: "py-3 sm:py-4 text-[11px] sm:text-[12px] text-[#99A1AF]", children: item.template }), _jsx("td", { className: "py-3 sm:py-4 text-[11px] sm:text-[12px] text-[#99A1AF]", children: item.startTime }), _jsx("td", { className: "py-3 sm:py-4 text-[11px] sm:text-[12px]", children: _jsx("span", { className: ongoing ? "text-[#99A1AF]" : "text-[#008236] font-semibold", children: item.status }) }), _jsx("td", { className: "py-3 sm:py-4 text-[11px] sm:text-[12px] text-[#99A1AF]", children: item.endTime }), _jsx("td", { className: "py-3 sm:py-4", children: ongoing ? (_jsx("button", { type: "button", onClick: () => onEndEvent(item.id), className: "cursor-pointer h-7 sm:h-8 px-3 sm:px-4 rounded-md bg-[#FF4B4B] text-white text-[10px] sm:text-[11px] font-semibold shadow-sm", children: "End Event" })) : (_jsx("div", { className: "h-7 sm:h-8 px-3 sm:px-4 rounded-md bg-[#E3E3E3] text-[#65AB82] text-[10px] sm:text-[11px] font-semibold inline-flex items-center justify-center", children: "Completed" })) }), _jsx("td", { className: "py-3 sm:py-4 text-right", children: ongoing ? (_jsx("button", { type: "button", onClick: () => onShareDetails(item.id), className: "cursor-pointer text-[11px] sm:text-[12px] font-semibold text-[#FD8F01]", children: "Share Details" })) : (_jsx("button", { type: "button", onClick: () => onViewReport(item.id), className: "cursor-pointer text-[11px] sm:text-[12px] font-medium text-[#747474]", children: "View Report" })) })] }));
}
